import type { Config } from "@netlify/functions";
import { createClient } from "@supabase/supabase-js";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
  "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
};

function json(data: unknown, status = 200) {
  return Response.json(data, {
    status,
    headers: corsHeaders,
  });
}

function getSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_KEY;

  if (!url || !key) {
    throw new Error("SUPABASE_URL or SUPABASE_KEY is not configured");
  }

  return createClient(url, key);
}

async function readBody(req: Request) {
  try {
    return await req.json();
  } catch {
    return null;
  }
}

export default async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const pathname = url.pathname.replace(/\/$/, "");

    // GET /api/health
    if (req.method === "GET" && pathname === "/api/health") {
      return json({ status: "success", message: "Backend работает!" });
    }

    const supabase = getSupabase();

    // GET /api/events
    if (req.method === "GET" && pathname === "/api/events") {
      const { data, error } = await supabase
        .from("events")
        .select("*")
        .order("start_date", { ascending: true, nullsFirst: false });

      if (error) {
        console.error("GET /api/events:", error);
        return json({ error: error.message }, 500);
      }

      return json(data ?? []);
    }


      if (req.method === "GET" && pathname === "/api/debug") {
        const key = process.env.SUPABASE_KEY;
      
        return json({
          hasUrl: !!process.env.SUPABASE_URL,
          hasKey: !!key,
          keyPrefix: key ? key.substring(0, 12) : null
        });
      }




    // POST /api/add-event
    if (req.method === "POST" && pathname === "/api/add-event") {
      const body = await readBody(req);

      if (!body || !body.title) {
        return json({ error: "Не указано название мероприятия" }, 400);
      }

      // id and created_at are generated by Supabase.
      const event = {
        title: body.title,
        status: body.status ?? "pending",
        description: body.description ?? null,
        start_date: body.start_date ?? null,
        end_date: body.end_date ?? null,
        price: body.price ?? null,
        image_url: body.image_url ?? null,
        source_url: body.source_url ?? null,
        broadcaster: body.broadcaster ?? null,
        "18+": body["18+"] ?? null,
      };

      const { data, error } = await supabase
        .from("events")
        .insert(event)
        .select()
        .single();

      if (error) {
        console.error("POST /api/add-event:", error);
        return json({ error: error.message }, 500);
      }

      return json(data, 201);
    }

    // POST /api/events/update
    if (req.method === "POST" && pathname === "/api/events/update") {
      const body = await readBody(req);

      if (!body || body.id === undefined || body.id === null) {
        return json({ error: "Не указан id мероприятия" }, 400);
      }

      const allowed = [
        "title",
        "status",
        "description",
        "start_date",
        "end_date",
        "price",
        "image_url",
        "source_url",
        "broadcaster",
        "18+",
      ];

      const update: Record<string, unknown> = {};
      for (const key of allowed) {
        if (Object.prototype.hasOwnProperty.call(body, key)) {
          update[key] = body[key];
        }
      }

      const { data, error } = await supabase
        .from("events")
        .update(update)
        .eq("id", body.id)
        .select()
        .single();

      if (error) {
        console.error("POST /api/events/update:", error);
        return json({ error: error.message }, 500);
      }

      return json(data);
    }

    // POST or DELETE /api/events/delete
    if (
      (req.method === "POST" || req.method === "DELETE") &&
      pathname === "/api/events/delete"
    ) {
      let body = await readBody(req);

      if (!body && req.method === "DELETE") {
        const id = new URL(req.url).searchParams.get("id");
        body = id ? { id } : null;
      }

      if (!body || body.id === undefined || body.id === null) {
        return json({ error: "Не указан id мероприятия" }, 400);
      }

      const { data, error } = await supabase
        .from("events")
        .delete()
        .eq("id", body.id)
        .select()
        .single();

      if (error) {
        console.error("DELETE /api/events/delete:", error);
        return json({ error: error.message }, 500);
      }

      return json({ success: true, event: data });
    }

    return json({ error: "Маршрут не найден" }, 404);
  } catch (error) {
    console.error("API error:", error);
    return json(
      {
        error: error instanceof Error ? error.message : "Внутренняя ошибка сервера",
      },
      500
    );
  }
};

export const config: Config = {
  path: ["/api", "/api/*"],
};
